spring:
  application:
    name: service
  redis:
    port: 6379
    host: redis_db    # docker-compose 中的service name
    password: 123456

  datasource:
    url: jdbc:mysql://mysql:3306/training
    username: root
    password: root
    type: com.mysql.cj.jdbc.MysqlDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: TrainningHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8080

log:
  name: service
  path: /home/syc/logs


count: 10




