
version: '2'

services:
  web:
    restart: always
    build:
      context: ./service1
    ports:
      - 8080
    volumes:
      - ./jars:/jars
      - ./logs:/logs
    networks:
      - dev
    depends_on:
      - redis_db
      - mysql
    links:
      - redis_db
      - mysql

  redis_db:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
    networks:
      - dev

  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
    networks:
      - dev


networks:
  dev:
    driver: bridge
